# -*- coding: utf-8 -*-
"""Projet AI face Mask Detection CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTHnxLnbtrhdcl_Quax-Y9HfEQBXoOX4
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
from zipfile import ZipFile
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

# Chemin du fichier zip uploadé
zip_path = "/content/archive.zip"

# Extraction
with ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content")

print(" Dataset extracted successfully")

import os
from zipfile import ZipFile, BadZipFile

zip_path = '/content/archive.zip'

if not os.path.exists(zip_path):
    print(f"Error: The file {zip_path} does not exist.")
elif os.path.isdir(zip_path):
    print(f"Error: {zip_path} is a directory, not a file.")
else:
    try:
        with ZipFile(zip_path, 'r') as zip_ref:
            print(f"{zip_path} is a valid zip file.")
    except BadZipFile:
        print(f"{zip_path} is not a valid zip file (BadZipFile error).")
    except Exception as e:
        print(f"An unexpected error occurred while checking {zip_path}: {e}")

dataset_path = "/content/data"

with_mask_path = os.path.join(dataset_path, "with_mask")
without_mask_path = os.path.join(dataset_path, "without_mask")

print("With mask path exists:", os.path.exists(with_mask_path))
print("Without mask path exists:", os.path.exists(without_mask_path))

with_mask_files = os.listdir(with_mask_path)
without_mask_files = os.listdir(without_mask_path)

print("With mask images:", len(with_mask_files))
print("Without mask images:", len(without_mask_files))

"""**Creating Labels for the two class of Images**

with mask  -->  1

without mask  -->  0
"""

with_mask_labels = [1] * len(with_mask_files)
without_mask_labels = [0] * len(without_mask_files)
labels = with_mask_labels + without_mask_labels

data = []

# Images avec masque
for img_file in with_mask_files:
    image = Image.open(os.path.join(with_mask_path, img_file))
    image = image.resize((128, 128))
    image = image.convert("RGB")
    data.append(np.array(image))

# Images sans masque
for img_file in without_mask_files:
    image = Image.open(os.path.join(without_mask_path, img_file))
    image = image.resize((128, 128))
    image = image.convert("RGB")
    data.append(np.array(image))

X = np.array(data)
Y = np.array(labels)

print("X shape:", X.shape)
print("Y shape:", Y.shape)

plt.imshow(X[0])
plt.title("With Mask")
plt.axis("off")
plt.show()

plt.imshow(X[-1])
plt.title("Without Mask")
plt.axis("off")
plt.show()

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=2
)

X_train = X_train / 255.0
X_test = X_test / 255.0

num_classes = 2

model = keras.Sequential([
    keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(128,128,3)),
    keras.layers.MaxPooling2D((2,2)),

    keras.layers.Conv2D(64, (3,3), activation='relu'),
    keras.layers.MaxPooling2D((2,2)),

    keras.layers.Flatten(),

    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.5),

    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(0.5),

    keras.layers.Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train, Y_train,
    validation_split=0.1,
    epochs=5,
    batch_size=32
)

loss, accuracy = model.evaluate(X_test, Y_test)
print("Test Accuracy:", accuracy)

plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.legend()
plt.show()

plt.plot(history.history['accuracy'], label='train accuracy')
plt.plot(history.history['val_accuracy'], label='val accuracy')
plt.legend()
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import numpy as np

Y_pred_probs = model.predict(X_test)
Y_pred_classes = np.argmax(Y_pred_probs, axis=1)

cm = confusion_matrix(Y_test, Y_pred_classes)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False,
            xticklabels=['Without Mask', 'With Mask'], yticklabels=['Without Mask', 'With Mask'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

print("Confusion Matrix:\n", cm)

import requests
from io import BytesIO

def predict_mask(image_source):
    if image_source.startswith('http://') or image_source.startswith('https://'):
        # Handle URL
        response = requests.get(image_source)
        image_data = BytesIO(response.content)
        image_np = np.asarray(bytearray(image_data.read()), dtype=np.uint8)
        image = cv2.imdecode(image_np, cv2.IMREAD_COLOR)
    else:
        # Handle local file path
        image = cv2.imread(image_source)

    if image is None:
        print(f" Error: Could not load image from {image_source}")
        return

    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (128,128))
    image = image / 255.0
    image = np.reshape(image, (1,128,128,3))

    prediction = model.predict(image)
    label = np.argmax(prediction)

    if label == 1:
        print(" Person WITH mask")
    else:
        print(" Person WITHOUT mask")

image_source = input("Please enter the image path or URL: ")
predict_mask(image_source)